export async function generateWebsite(prompt){

const html = `
<!DOCTYPE html>
<html>
<head>
<title>${prompt}</title>
<link rel="stylesheet" href="style.css">
</head>

<body>

<header>
<h1>${prompt}</h1>
<p>Website generated by Ayman AI</p>
</header>

<section>
<h2>Welcome</h2>
<p>This website was automatically generated.</p>
</section>

<footer>
<p>Powered by Ayman AI</p>
</footer>

</body>
</html>
`

const css = `
body{
font-family:Arial;
background:#0f172a;
color:white;
text-align:center;
padding:40px;
}

header{
background:#020617;
padding:40px;
}
`

return {html,css}

}